import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Terms of Service | NovaBridge Agency",
};

export default function TermsPage() {
  return (
    <main className="bg-background min-h-screen">
      <Navigation />
      
      <div className="pt-40 pb-20 container mx-auto px-6">
        <div className="max-w-4xl mx-auto bg-secondary p-12 rounded-3xl border border-white/5">
          <h1 className="text-4xl font-bold font-clash mb-10 border-b border-white/10 pb-6">Terms of Service</h1>
          
          <div className="prose prose-invert max-w-none text-muted">
            <p>Last Updated: {new Date().toLocaleDateString()}</p>
            
            <h3 className="text-white mt-8 mb-4 font-bold text-xl">1. Intellectual Property</h3>
            <p>All proprietary funnels, email architectures, and automation infrastructures generated by NovaBridge remain our licensed IP unless specifically transferred under an enterprise contract.</p>
            
            <h3 className="text-white mt-8 mb-4 font-bold text-xl">2. Lead Scraps & Outreach Compliance</h3>
            <p>By engaging with our outreach solutions or filling out an audit, you authorize NovaBridge algorithms to interact with you via provided channels.</p>
            
            <h3 className="text-white mt-8 mb-4 font-bold text-xl">3. Liability Disclaimer</h3>
            <p>Metrics depicted in Case Studies represent isolated successful campaigns and do not constitute a blanket revenue guarantee. We provide technical infrastructure, not specific fiscal assurances.</p>
          </div>
        </div>
      </div>
      
      <Footer />
    </main>
  );
}
